version: '3.8'

services:
  bank_manager:
    container_name: bank_manager_server
    cap_drop:
      - ALL
    build:
      context: .
    env_file:
      - env/.env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - mongo
    networks:
      - db

networks:
  db:
    name: db-network
    external: true
